name: xvpn
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  flutter_riverpod: ^3.0.1                # [ DI / State Managment            ]
  hive: ^2.2.3                            # [ Основное локальное хранилище    ]
  hive_flutter: ^1.1.0
  flutter_svg: ^2.1.0                     # [ Работа с svg (для иконок)       ] 
  dartz: ^0.10.1                          # [ Right-Left Generics механика    ]
  dio: ^5.9.0                             # [ Api client                      ]
  equatable: ^2.0.7                       # [ Сравнения / переопределения     ]
  google_fonts: ^6.3.0                    # [ Шрифты                          ]
  flutter_secure_storage: ^10.0.0         # [ Защищённое локальное хранилище  ]
  flutter_spinkit: ^5.2.2                 # [ Виджеты загрузки страницы       ]
  flutter_staggered_animations: ^1.1.1
  flutter_typeahead: ^5.2.0
  introduction_screen: ^4.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  hive_dev_tools: ^0.0.1

dependency_overrides:
  intl: ^0.20.2

flutter:
  uses-material-design: true
  assets:
    # [ Иконки ]
    - assets/icons/icon_connnection_disconnected.svg
    - assets/icons/icon_connnection_connecting.svg
    - assets/icons/icon_connnection_connected.svg
    - assets/icons/icon_transaction.svg
    - assets/icons/icon_arrow_right.svg
    - assets/icons/icon_arrow_down.svg
    - assets/icons/icon_premium.svg
    - assets/icons/icon_price.svg

    # [ Баннеры ]
    - assets/banners/banner_onboarding.png
    - assets/banners/banner_need_work.png
    - assets/banners/banner_premium.png
  
    # [ Иконки стран ]
    - assets/countries/img_country_usa.png